name: Deploy to reg.ru VPS (SSH-clone support)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH agent for VPS key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Copy repo deploy key to server (optional)
        if: ${{ secrets.REPO_SSH_PRIVATE_KEY != '' }}
        env:
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_PORT: ${{ secrets.VPS_SSH_PORT || '22' }}
        run: |
          echo "Transferring repo deploy key to server"
          tmpdir=$(mktemp -d)
          cat > "$tmpdir/repo_deploy_key" <<'KEY'
${{ secrets.REPO_SSH_PRIVATE_KEY }}
KEY
          chmod 600 "$tmpdir/repo_deploy_key"
          scp -P ${SSH_PORT} "$tmpdir/repo_deploy_key" ${SSH_USER}@${SSH_HOST}:/tmp/repo_deploy_key
          # On the server: move key into ~/.ssh, configure ssh config for github.com and set proper permissions
          ssh -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} "bash -lc 'set -e; mkdir -p ~/.ssh; mv /tmp/repo_deploy_key ~/.ssh/repo_deploy_key; chmod 600 ~/.ssh/repo_deploy_key; grep -q "Host github.com" ~/.ssh/config 2>/dev/null || cat >> ~/.ssh/config <<'CFG'
Host github.com
  HostName github.com
  IdentityFile ~/.ssh/repo_deploy_key
  IdentitiesOnly yes
CFG
; chmod 600 ~/.ssh/config'"

      - name: Deploy on server (clone/pull + docker compose)
        env:
          DEPLOY_PATH: ${{ secrets.VPS_DEPLOY_PATH || '/var/www/faceit-ai-bot' }}
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_HOST: ${{ secrets.VPS_HOST }}
          SSH_PORT: ${{ secrets.VPS_SSH_PORT || '22' }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          echo "Deploying to ${SSH_USER}@${SSH_HOST}:${DEPLOY_PATH}"
          # If REPO_SSH is set, attempt SSH clone; otherwise use HTTPS
          # Try SSH clone on server if repo_deploy_key exists (uploaded earlier by this workflow)
          ssh -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} "bash -lc '
            set -e
            if [ -d "${DEPLOY_PATH}/.git" ]; then
              cd "${DEPLOY_PATH}" && git pull || true
            else
              if [ -f ~/.ssh/repo_deploy_key ]; then
                echo "Cloning via SSH"
                git clone git@github.com:${GITHUB_REPO}.git "${DEPLOY_PATH}"
              else
                echo "Cloning via HTTPS"
                git clone https://github.com/${GITHUB_REPO}.git "${DEPLOY_PATH}"
              fi
            fi
            cd "${DEPLOY_PATH}"
            docker compose pull || true
            docker compose up -d --build
          '
